<a href="https://colab.research.google.com/github/tomaslizazu1/Proyecto_Dao/blob/main/ETL_Compras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Sprint 21/5 → 4/06

Archivo = 'Compras2025.xlsx'

* Tareas:

[ ] Lee los 12 archivos COMPRAS de la carpeta COMPRAS

[ ] Filtra solo filas FC (facturas), excluye PA (pagos)

[ ] Excluye el proveedor EMPRENDIMIENTOS 30002 (ese lo cubre P2/WEG)

[ ] Columnas de salida: fecha, mes, proveedor, concepto, neto

[ ] DataFrame sin duplicados ni filas vacías

[ ] Documentado con docstring y comentarios

Output: df_compras — una fila por factura de compra, 12 meses

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel('Compras2025.xlsx')

#1. Normalizar nombre de columas

df.columns = (
    df.columns.str.strip().str.lower().str.replace(' ', '_')
)

In [ ]:
#1. Filtro de columnas mantener FC(facturas) - excluir PA(pagos)
#Ejemplo - excluir 'PA-A-1-1019'

df = df[df['cpte.'].str.startswith('FC')]
df = df[~df['cpte.'].str.startswith('PA')]

df.head(5)

,cpte.,fecha,mon.,cot.,total,saldo,iva,neto,contacto,concepto_caja,concepto,observaciones,usuario,viajante,fec._entrega,cond._pago
0,FC-A-1326-2133217,2025-01-01,$,1,-127836.95,0.0,-23889.75,-103947.20,(30032) AMX ARGENTINA SA CLARO,NaN,NaN,NaN,CECILIA,NaN,NaN,Ctacte
1,FC-A-3-102960,2025-01-01,$,1,-22500.00,0.0,-3904.96,-18595.04,(30006) AGUARED,NaN,NaN,NaN,CECILIA,NaN,NaN,10 Dias Ff
2,FC-A-3-145060,2025-01-02,$,1,-57660.01,0.0,-10007.11,-47652.90,(30007) DEMARCHI ELECTRONICA,NaN,NaN,NaN,CECILIA,NaN,NaN,30 Dias Ff
3,FC-A-5-61870,2025-01-02,$,1,-88925.78,0.0,-18905.48,-70020.30,(30005) COOP. TELEF. VGG LTDA,NaN,NaN,NaN,CECILIA,NaN,NaN,21 Dias Ff
4,FC-A-5-61336,2025-01-02,$,1,-10702.81,0.0,-2182.06,-8520.75,(30005) COOP. TELEF. VGG LTDA,NaN,NaN,NaN,CECILIA,NaN,NaN,21 Dias Ff

In [ ]:
#2. Excluir proveedor = EMPRENDIMIENTOS 30002

df = df[df['contacto'] != 'EMPRENDIMIENTOS 30002']

#3. Columnas de salida

df = df[['fecha', 'contacto', 'concepto', 'neto']].copy()

#Ordenar x mes

df['fecha'] = pd.to_datetime(df['fecha'])
df['mes'] = df['fecha'].dt.month

df[['fecha', 'mes']]

         fecha  mes
0   2025-01-01    1
1   2025-01-01    1
2   2025-01-02    1
3   2025-01-02    1
4   2025-01-02    1
..         ...  ...
277 2025-12-18   12
278 2025-12-19   12
279 2025-12-19   12
280 2025-12-24   12
281 2025-12-31   12

[276 rows x 2 columns]

In [ ]:
#4. Eliminar vacíos y duplicados
lista_df = []


df = df.dropna(how = 'all')
lista_df.append(df)

#concatenar

df_compras = pd.concat(
    lista_df,
    ignore_index=True
)

#eliminar duplicados

df_compras = df_compras.drop_duplicates()
df_compras = df_compras.reset_index(drop=True)

df_compras[['fecha', 'mes', 'contacto', 'concepto', 'neto']]   #Output

,fecha,mes,contacto,concepto,neto
0,2025-01-01,1,(30032) AMX ARGENTINA SA CLARO,NaN,-103947.20
1,2025-01-01,1,(30006) AGUARED,NaN,-18595.04
2,2025-01-02,1,(30007) DEMARCHI ELECTRONICA,NaN,-47652.90
3,2025-01-02,1,(30005) COOP. TELEF. VGG LTDA,NaN,-70020.30
4,2025-01-02,1,(30005) COOP. TELEF. VGG LTDA,NaN,-8520.75
...,...,...,...,...,...
271,2025-12-18,12,(30018) COOPERATIVA INTEGRAL DE VGG,NaN,-736166.23
272,2025-12-19,12,(30094) MANCHADO EDGARDO JOSE,NaN,-56000.00
273,2025-12-19,12,(30062) ACEROS CHUBUT SRL,NaN,-38689.44
274,2025-12-24,12,(30175) OXITODO SA,NaN,-84546.00
275,2025-12-31,12,(30022) SAN CRISTOBAL SEGUROS,PLAN DE AHORRO CAMION MERCEDES CUOTA 31,-93829.58

In [ ]:
df_compras.to_csv('df_compras.csv', index=False, encoding='utf-8-sig')

# 2. Forzar la descarga automática al escritorio/computadora
from google.colab import files
files.download('df_compras.csv')